# ShellCommand: https://github.com/XUJINKAI/ShellCommand 

- Name: Publish win-x64 Release
  Command: dotnet publish -c Release -r win-x64 -o publish-win-release /p:PublishSingleFile=true /p:PublishTrimmed=true cipherc/cipherc.csproj

- Name: Publish win-x64 Debug
  Command: dotnet publish -c Debug -r win-x64 -o publish-win-debug /p:PublishSingleFile=true /p:PublishTrimmed=true cipherc/cipherc.csproj

- Name: Publish linux-x64 Release
  Command: dotnet publish -c Release -r linux-x64 -o publish-linux-release /p:PublishSingleFile=true /p:PublishTrimmed=true cipherc/cipherc.csproj

- Name: Publish linux-x64 Debug
  Command: dotnet publish -c Debug -r linux-x64 -o publish-linux-debug /p:PublishSingleFile=true /p:PublishTrimmed=true cipherc/cipherc.csproj
